module SiteConstants
	TUMOR_TYPES = {
		laml: 'Acute Myeloid Leukemia',
		acc:  'Adrenocortical carcinoma',
		blca: 'Bladder Urothelial Carcinoma',
		lgg:  'Brain Lower Grade Glioma',
		brca: 'Breast invasive carcinoma',
		cesc: 'Cervical squamous cell carcinoma and endocervical adenocarcinoma',
		chol: 'Cholangiocarcinoma',
		coad: 'Colon adenocarcinoma',
		esca: 'Esophageal carcinoma',
		gbm:  'Glioblastoma multiforme',
		hnsc: 'Head and Neck squamous cell carcinoma',
		kich: 'Kidney Chromophobe',
		kirc: 'Kidney renal clear cell carcinoma',
		kirp: 'Kidney renal papillary cell carcinoma',
		lihc: 'Liver hepatocellular carcinoma',
		luad: 'Lung adenocarcinoma',
		lusc: 'Lung squamous cell carcinoma',
		dlbc: 'Lymphoid Neoplasm Diffuse Large B-cell Lymphoma',
		meso: 'Mesothelioma',
		ov:   'Ovarian serous cystadenocarcinoma', 
		paad: 'Pancreatic adenocarcinoma', 
		pcpg: 'Pheochromocytoma and Paraganglioma',
		prad: 'Prostate adenocarcinoma', 
		read: 'Rectum adenocarcinoma',
		sarc: 'Sarcoma',
		skcm: 'Skin Cutaneous Melanoma',
		stad: 'Stomach adenocarcinoma',
		tgct: 'Testicular Germ Cell Tumors',
		thym: 'Thymoma',
		thca: 'Thyroid carcinoma',
		ucs:  'Uterine Carcinosarcoma',
		ucec: 'Uterine Corpus Endometrial Carcinoma',
		uvm:  'Uveal Melanoma' 
	}
end
